=== jeanbabtista/college/src/main/kotlin/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="infected">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="person" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1" />
                                        <xs:maxInclusive value="1000" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="fname" type="xs:string" />
                            <xs:element name="lname" type="xs:string" />
                            <xs:element name="age" type="xs:float" />
                            <xs:element name="location" type="xs:string" />

                            <xs:element name="sex">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="male" />
                                        <xs:enumeration value="female" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="birthdate">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(0[1-9]|[12][0-9]|3[01]).(0[1-9]|1[012]).(19|20)\d\d" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="education" type="xs:string" />
                            <xs:element name="description" type="xs:string" />

                            <xs:element name="images">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!-- Type should be base64Binary -->
                                        <xs:element name="image" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="infection-rate">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1" />
                                        <xs:maxInclusive value="10" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== jeanbabtista/college/src/main/kotlin/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<infected xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schema.xsd">
    <person>
        <id>1</id>
        <fname>a</fname>
        <lname>a</lname>
        <age>21</age>
        <location>a</location>
        <sex>female</sex>
        <birthdate>01.01.2001</birthdate>
        <education>College</education>
        <description>Sick and ill</description>
        <images>
            <image>image1.png</image>
            <image>image2.png</image>
        </images>
        <infection-rate>1</infection-rate>
    </person>
    <person>
        <id>2</id>
        <fname>b</fname>
        <lname>b</lname>
        <age>22</age>
        <location>b</location>
        <sex>male</sex>
        <birthdate>01.01.2002</birthdate>
        <education>College</education>
        <description>Sick and ill</description>
        <images>
            <image>image1.png</image>
            <image>image2.png</image>
        </images>
        <infection-rate>2</infection-rate>
    </person>
    <person>
        <id>4</id>
        <fname>d</fname>
        <lname>d</lname>
        <age>24</age>
        <location>d</location>
        <sex>male</sex>
        <birthdate>01.01.2004</birthdate>
        <education>College</education>
        <description>Sick and ill</description>
        <images>
            <image>image1.png</image>
            <image>image2.png</image>
        </images>
        <infection-rate>4</infection-rate>
    </person>
    <person>
        <id>5</id>
        <fname>e</fname>
        <lname>e</lname>
        <age>25</age>
        <location>e</location>
        <sex>female</sex>
        <birthdate>01.01.2005</birthdate>
        <education>College</education>
        <description>Sick and ill</description>
        <images>
            <image>image1.png</image>
            <image>image2.png</image>
        </images>
        <infection-rate>5</infection-rate>
    </person>
    <person>
        <id>1</id>
        <fname>a</fname>
        <lname>a</lname>
        <age>21</age>
        <location>a</location>
        <sex>female</sex>
        <birthdate>01.01.2001</birthdate>
        <education>College</education>
        <description>Sick and ill</description>
        <images>
            <image>image1.png</image>
            <image>image2.png</image>
        </images>
        <infection-rate>1</infection-rate>
    </person>
    <person>
        <id>2</id>
        <fname>b</fname>
        <lname>b</lname>
        <age>22</age>
        <location>b</location>
        <sex>male</sex>
        <birthdate>01.01.2002</birthdate>
        <education>College</education>
        <description>Sick and ill</description>
        <images>
            <image>image1.png</image>
            <image>image2.png</image>
        </images>
        <infection-rate>2</infection-rate>
    </person>
    <person>
        <id>4</id>
        <fname>d</fname>
        <lname>d</lname>
        <age>24</age>
        <location>d</location>
        <sex>male</sex>
        <birthdate>01.01.2004</birthdate>
        <education>College</education>
        <description>Sick and ill</description>
        <images>
            <image>image1.png</image>
            <image>image2.png</image>
        </images>
        <infection-rate>4</infection-rate>
    </person>
    <person>
        <id>5</id>
        <fname>e</fname>
        <lname>e</lname>
        <age>25</age>
        <location>e</location>
        <sex>female</sex>
        <birthdate>01.01.2005</birthdate>
        <education>College</education>
        <description>Sick and ill</description>
        <images>
            <image>image1.png</image>
            <image>image2.png</image>
        </images>
        <infection-rate>5</infection-rate>
    </person>
</infected>
